### ISSUE TITLE
No puedes dañar entidades de tipo MAGMA_CUBE en este lugar

### ISSUE THREAD

**Issue by JhordanPG** [Wirlie/ProtectionBlocks-Incidencias#1]
Al tener el flag activo de golpeo , sale ese mensaje de no puedes dañar entidades de tipo MAGMA_CUBE

Prueba: https://gyazo.com/767a1719737fcbfafaca06282a621ead

**Comment by Wirlie** [comment]
Error de redacción del flag actual, mejora: agregar un flag adicional.

**Comment by Wirlie** [comment]
Corregido en la última versión ✅
