### ISSUE TITLE
Cambiar el tipo de muestreo del límite barriers solo existen en java y no en bedrock, los de bedrock no ven nada, podría ser lo que se muestra cuando llegas al límite del mundo o partículas.

### ISSUE THREAD

**Issue by JhordanPG** [Wirlie/ProtectionBlocks-Incidencias#2]
![image](https://user-images.githubusercontent.com/42554918/186062441-e98c22da-2397-4c05-bc8a-1c335a8e2775.png)

**Comment by JhordanPG** [comment]
Ah de paso arreglar el mensaje que muestra "/ps limits", que sea /pb limits , al acabarse la visualización del /pb limits, sale ese mensaje

**Comment by JhordanPG** [comment]
![image](https://user-images.githubusercontent.com/42554918/186066107-00816df8-6b5c-4edb-858f-d9ba81b7595e.png)

**Comment by Wirlie** [comment]
Corregido en la última versión ✅
