### ISSUE TITLE
No se puede añadir jugadores offline a la prote

### ISSUE THREAD

**Issue by JhordanPG** [Wirlie/ProtectionBlocks-Incidencias#4]
![image](https://user-images.githubusercontent.com/42554918/186063136-becc3637-f5ec-4ebf-850f-89c1d0c9d8b0.png)

**Comment by Wirlie** [comment]
Relacionado al comando /pb add , pero en el menú de /pb edit si deja agregar jugadores offline.

**Comment by Wirlie** [comment]
**Hipótesis:** La lógica del Menú del comando /pb edit se encuentra separado de la lógica del comando /pb add y por tanto ambos comandos poseen su propia lógica, a pesar de que ambos hacen la misma función.

**Solución:** Extraer la lógica y hacer que tanto el comando /pb edit como el comando /pb add compartan las mismas reglas y validaciones.
