### ISSUE TITLE
Las personas pueden romper carteles de PRIVADO de BlockLocker estando dentro de una protección

### ISSUE THREAD

**Issue by JhordanPG** [Wirlie/ProtectionBlocks-Incidencias#6]
Pruebas
https://user-images.githubusercontent.com/42554918/186231601-88186e9a-d91f-479d-8625-521b27724782.mp4

**Comment by JhordanPG** [comment]
Pero si no hay una prote ya no le deja romper.

**Comment by Wirlie** [comment]
Solucionado en la última versión del plugin ✅
